name: Publish

on:
  push:
    tags:
      - 'v*'


permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@ch'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Create .npmrc dynamically
        run: |
          echo "@ch:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Publish
        run: npm publish --registry=https://npm.pkg.github.com/ --access=restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  